authtoken: bdb0ff0196744ef4a9a3ed8cb8e37613
client_id: 550733a27e8a435faa257d7adfa09662
cloud_server_addr: zns1012.fzv2.zeronews.cc:7000
tls_ca_cert: |
    -----BEGIN CERTIFICATE-----
    MIIBwDCCAWagAwIBAgIQF4TKiWDqk3tXw/yVLC+sBDAKBggqhkjOPQQDAjAjMSEw
    HwYDVQQDExh6bnMxMDEyLmZ6djIuemVyb25ld3MuY2MwHhcNMjYwNDI2MDYyMzMw
    WhcNMzYwNDI2MDcyMzMwWjAjMSEwHwYDVQQDExh6bnMxMDEyLmZ6djIuemVyb25l
    d3MuY2MwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQ9XpQb2HI6Wd/XcQG3sY1n
    4RiOIfKUHL5wOF2Kt7fBL9POtkYhXRmoNo4JnTWSO2VrgvPd6x5nArM/rDk5+/E6
    o3wwejAOBgNVHQ8BAf8EBAMCBaAwEwYDVR0lBAwwCgYIKwYBBQUHAwEwDwYDVR0T
    AQH/BAUwAwEB/zAdBgNVHQ4EFgQU5Q1IJsN/l/oBEVDcrhbG0NI5aUAwIwYDVR0R
    BBwwGoIYem5zMTAxMi5menYyLnplcm9uZXdzLmNjMAoGCCqGSM49BAMCA0gAMEUC
    IQCWoPlGj6dN7TGYK9N9wxr1WbOXtRfVk3LnJDmVUFuhoAIgK2ictN8Vi2PENThl
    erO5IQWCqx0GMFTdjl9BP8HRQM0=
    -----END CERTIFICATE-----
